# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.


# Setup
title:               PKACTION
tagline:             'Thoughts on gaming'
description:         'Just opinions from an old gamer.  Recently a fan of <a href="http://dota2.com" target="_blank">Dota 2</a>.'
url:                 http://pkaction.com
baseurl:             ''
paginate:            2

# About/contact
author:
  name:              DHF
  url:               https://github.com/pkaction
  email:             

# Custom vars
version:             1.0.0
